// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/param.proto

package api_v1

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PaginationParam) Validate() error {
	return nil
}
func (this *PaginationResponse) Validate() error {
	return nil
}
